### ISSUE TITLE
node error WIN 10 MAX 8.0.4 - node script not running

### ISSUE THREAD

**Issue by sone** [MusicSDP/source-code#1]
hi, after upgrading to newest sources today the following messages are printed to the max console:

node.script: Node script not running, can't handle message msdpfs
node.script: Node script not running, can't handle message update
node.script: Node script not running, can't handle message newProject
maxurl: Error parsing the json, adding body to dict as string.

best, j.

**Comment by hughlobel** [comment]
Tested on two Win10 installs, both running 8.0.4, could not replicate issue.

I need some more information if you need help honing in on the issue:

Can you tell me more about when you are receiving these messages? Is it on launch, when attempting to open a project, or while running a project?

Are there any issues occurring in MSDP when these messages appear? Is it keeping anything from working?

Are you modifying MSDP's code in any way?

What are the specs of your computer?

**Comment by sone** [comment]
I moved the source code from my second internal drive D: to C: into the users Documents MAX 8 Projects folder and everything is working fine now. My problem is solved. If it's from interest to find out why it's not working if the sources are placed on drive D: I could investigate but I assume it's related to folder attributes, probably specific to my installation and/or related to a sometimes occuring problem with Windows 10 so I close this issue.

**Comment by hughlobel** [comment]
Glad it's working. I run the code from the D: drive on my own computer, so I don't think that's the cause of the problem. Thanks for following up though!
