### ISSUE TITLE
Hardware Clock Module

### ISSUE THREAD

**Issue by Eurikon** [MusicSDP/source-code#2]
Hi,
will there be a clock sync module anytime soon? 

One that can send out an analog type clock sync, as in the modular synth world. 
So that for example MSDP could be clock master,  and a program such as VCV Rack could sync to that clock signal.

**Comment by hughlobel** [comment]
I will be building more interoperability modules in the future, and clock sync is something that is a pretty important focus. I can’t say when a module will come out with that feature right now though, sorry.

However, you can use Ableton Link if you’d like to sync the metronome between various platforms. If you look at the System Console, and check out the middle of the Metronome, you’ll find a ‘Clock Source’ drop down menu. Setting source from ‘Internal’ to ‘Link’ will make the metronome an Ableton Link slave, meaning it can be controlled by any networked Link Master program. If you can find an Ableton Link master module for VCV rack, you could sync with that today!

As a final note, the Link feature is not thoroughly tested, so I’m not sure what problems you will or won’t encounter. If you decide to try it, I would LOVE to hear about your experience!

**Comment by Eurikon** [comment]
Ok, thanks for replying.
Hope sync module will get higher on the list in the very near future.

I will let you know how Ableton Link functions performs if I use it sometime.

Side note: from version v3.0 Link has start/stop added to the protocol. This is a significant usability improvement. 
If that has not added yet to the implemented Link in MSDP, then please do take a look at it for the time being. 

http://www.synthtopia.com/content/2018/02/21/ableton-link-v3-adds-start-stop-control/amp/
